### ISSUE TITLE
video/H264

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-stream-mappings#2]
### IANA Registration

https://www.iana.org/assignments/media-types/video/H264

### IETF RFC

https://datatracker.ietf.org/doc/html/rfc6184

### Parameters

* Optional parameters (see [RFC 6184 Section 8.2.3](https://datatracker.ietf.org/doc/html/rfc6184#section-8.2.3))
    * `profile-level-id`
    * `sprop-parameter-sets`
    * `sprop-level-parameter-sets`
    * `packetization-mode`
    * `sprop-interleaving-depth`
    * `sprop-deint-buf-req`
    * `sprop-init-buf-time`
    * `sprop-max-don-diff`
    * Note: there are also a large number of H264 receiver capabilities defined which could potentially be mapped to BCP-004-01 Receiver Capabilities?

**Comment by garethsb** [comment]
Initial proposal:
* `profile-level-id` should be mapped into IS-04 Flow
* `packetization-mode` should be mapped into IS-04 Sender
* `sprop-parameter-sets`, while important for out-of-band configuration of a decoder, is not suitable for a Controller to process, and most of the information carried in this parameter is already carried in the IS-04 Flow (frame width and height, frame rate, scan, etc.)

**Comment by garethsb** [comment]
Update based on initial implementation feedback within the AMWA NMOS Cloud Testbed + New Formats ad-hoc group.
Our conclusion is that we should use separate, string-valued, `profile` and `level` Flow attributes and matching Receiver parameter constraints. This enables human-readability and common handling in Controllers with other compression formats that use similarly defined arrangements of profile and level, such as JPEG XS, H.265, etc.

Since we now propose string values, these need to be enumerated.

**Comment by garethsb** [comment]
As well as mapping SDP `profile-level-id` to NMOS Flow `profile` and `level`, the SDP `packetization-mode` could be mapped to NMOS Sender `packet_transmission_mode` with three permitted values: `"single_nal_unit_mode"`, `"non_interleaved_mode"`, `"interleaved_mode"`.

**Comment by peterbrightwell** [comment]
@garethsb can you check this is all covered in the BCP-006-02 if still required.
Architecture Review Group review: closing.
