### ISSUE TITLE
video/H265

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-stream-mappings#3]
### IANA Registration

https://www.iana.org/assignments/media-types/video/H265

### IETF RFC

https://datatracker.ietf.org/doc/html/rfc7798

### Parameters

* Optional parameters
    * `profile-space`
    * `profile-id`
    * `tier-flag`
    * `level-id`
    * `profile-compatibility-indicator`
    * `sprop-sub-layer-id`
    * `tx-mode`
    * `sprop-vps`
    * `sprop-sps`
    * `sprop-pps`
    * `sprop-sei`
    * `sprop-max-don-diff`
    * `sprop-depack-buf-nalus`
    * `sprop-depack-buf-bytes`
    * `sprop-segmentation-id`
    * `sprop-spatial-segmentation-idc`
    * Note: there are also a large number of H265 receiver capabilities defined which could be mapped to BCP-004-01 Receiver Capabilities?
 
Initial proposal:
* `profile-space`, `profile-id`, `tier-flag` and `level-id` should be mapped into IS-04 Flow

**Comment by garethsb** [comment]
Update based on initial implementation feedback within the AMWA NMOS Cloud Testbed + New Formats ad-hoc group.
Our conclusion is that we should use separate, string-valued, profile and level Flow attributes and matching Receiver parameter constraints. This enables human-readability and common handling in Controllers with other compression formats that use similarly defined arrangements of profile and level, such as JPEG XS, H.264, etc.

Since we now propose string values, these need to be enumerated and related to `profile-space`, `profile-id`, `tier-flag` and `level-id`.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: Closing as covered by bcp-006-03 activity Work In Progress
